//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMono {
	
	
	public partial class Site {
		
		protected System.Web.UI.WebControls.Button btnRestart;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	}
}
