//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMono {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.ImageButton btnLeftCat;
		
		protected System.Web.UI.WebControls.HiddenField leftCatId;
		
		protected System.Web.UI.WebControls.ImageButton btnRightCat;
		
		protected System.Web.UI.WebControls.HiddenField rightCatId;
		
		protected System.Web.UI.WebControls.Button nextCats;
	}
}
