//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMono {
	
	
	public partial class Scores {
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.CheckBox chkAll;
		
		protected System.Web.UI.WebControls.Repeater rptCats;
		
		protected System.Web.UI.WebControls.Image imgCat;
		
		protected System.Web.UI.WebControls.Label lblCatScore;
		
		protected System.Web.UI.WebControls.Label lblNbVotes;
	}
}
